### ISSUE TITLE
Add a build process

### ISSUE THREAD

**Issue by YummyBacon5** [likes-gay/Cave-of-Shadows#4]
We are going to be using [PyInstaller](https://pyinstaller.org/en/stable/) to bundle our Python files into an exe. To allow for an easier process to run the game, rather than having to clone the repository. (#3 is related)

@Zoobdude has said he will create a GitHub Action that automatically does this for us.

**Comment by YummyBacon5** [comment]
This has now beed added for Windows, but a version still needs to be made for Linux

https://github.com/likes-gay/AdventureSoft-Task-2/releases

**Comment by Zoobdude** [comment]
Build now works for Linux and Windows as of commit https://github.com/likes-gay/Cave-of-Shadows/commit/b1420530742975f6fc6c19e5140590d49e47d57c run https://github.com/likes-gay/Cave-of-Shadows/actions/runs/12350565536
